package com.butterflymob.entity;

public class Appinfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appinfo.appkey
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    private String appkey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appinfo.name
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appinfo.appsecret
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    private String appsecret;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appinfo.disp
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    private String disp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appinfo.category
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    private String category;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appinfo.logo
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    private String logo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appinfo.appkey
     *
     * @return the value of appinfo.appkey
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    public String getAppkey() {
        return appkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appinfo.appkey
     *
     * @param appkey the value for appinfo.appkey
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    public void setAppkey(String appkey) {
        this.appkey = appkey == null ? null : appkey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appinfo.name
     *
     * @return the value of appinfo.name
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appinfo.name
     *
     * @param name the value for appinfo.name
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appinfo.appsecret
     *
     * @return the value of appinfo.appsecret
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    public String getAppsecret() {
        return appsecret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appinfo.appsecret
     *
     * @param appsecret the value for appinfo.appsecret
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    public void setAppsecret(String appsecret) {
        this.appsecret = appsecret == null ? null : appsecret.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appinfo.disp
     *
     * @return the value of appinfo.disp
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    public String getDisp() {
        return disp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appinfo.disp
     *
     * @param disp the value for appinfo.disp
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    public void setDisp(String disp) {
        this.disp = disp == null ? null : disp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appinfo.category
     *
     * @return the value of appinfo.category
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appinfo.category
     *
     * @param category the value for appinfo.category
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appinfo.logo
     *
     * @return the value of appinfo.logo
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    public String getLogo() {
        return logo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appinfo.logo
     *
     * @param logo the value for appinfo.logo
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    public void setLogo(String logo) {
        this.logo = logo == null ? null : logo.trim();
    }
}