package com.butterflymob.entity;

import java.util.ArrayList;
import java.util.List;

public class OfforonExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table offOron
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table offOron
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table offOron
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offOron
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    public OfforonExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offOron
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offOron
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offOron
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offOron
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offOron
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offOron
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offOron
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offOron
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offOron
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offOron
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table offOron
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIstshortlinkIsNull() {
            addCriterion("isTshortlink is null");
            return (Criteria) this;
        }

        public Criteria andIstshortlinkIsNotNull() {
            addCriterion("isTshortlink is not null");
            return (Criteria) this;
        }

        public Criteria andIstshortlinkEqualTo(Integer value) {
            addCriterion("isTshortlink =", value, "istshortlink");
            return (Criteria) this;
        }

        public Criteria andIstshortlinkNotEqualTo(Integer value) {
            addCriterion("isTshortlink <>", value, "istshortlink");
            return (Criteria) this;
        }

        public Criteria andIstshortlinkGreaterThan(Integer value) {
            addCriterion("isTshortlink >", value, "istshortlink");
            return (Criteria) this;
        }

        public Criteria andIstshortlinkGreaterThanOrEqualTo(Integer value) {
            addCriterion("isTshortlink >=", value, "istshortlink");
            return (Criteria) this;
        }

        public Criteria andIstshortlinkLessThan(Integer value) {
            addCriterion("isTshortlink <", value, "istshortlink");
            return (Criteria) this;
        }

        public Criteria andIstshortlinkLessThanOrEqualTo(Integer value) {
            addCriterion("isTshortlink <=", value, "istshortlink");
            return (Criteria) this;
        }

        public Criteria andIstshortlinkIn(List<Integer> values) {
            addCriterion("isTshortlink in", values, "istshortlink");
            return (Criteria) this;
        }

        public Criteria andIstshortlinkNotIn(List<Integer> values) {
            addCriterion("isTshortlink not in", values, "istshortlink");
            return (Criteria) this;
        }

        public Criteria andIstshortlinkBetween(Integer value1, Integer value2) {
            addCriterion("isTshortlink between", value1, value2, "istshortlink");
            return (Criteria) this;
        }

        public Criteria andIstshortlinkNotBetween(Integer value1, Integer value2) {
            addCriterion("isTshortlink not between", value1, value2, "istshortlink");
            return (Criteria) this;
        }

        public Criteria andIsopenstateIsNull() {
            addCriterion("isOpenState is null");
            return (Criteria) this;
        }

        public Criteria andIsopenstateIsNotNull() {
            addCriterion("isOpenState is not null");
            return (Criteria) this;
        }

        public Criteria andIsopenstateEqualTo(Integer value) {
            addCriterion("isOpenState =", value, "isopenstate");
            return (Criteria) this;
        }

        public Criteria andIsopenstateNotEqualTo(Integer value) {
            addCriterion("isOpenState <>", value, "isopenstate");
            return (Criteria) this;
        }

        public Criteria andIsopenstateGreaterThan(Integer value) {
            addCriterion("isOpenState >", value, "isopenstate");
            return (Criteria) this;
        }

        public Criteria andIsopenstateGreaterThanOrEqualTo(Integer value) {
            addCriterion("isOpenState >=", value, "isopenstate");
            return (Criteria) this;
        }

        public Criteria andIsopenstateLessThan(Integer value) {
            addCriterion("isOpenState <", value, "isopenstate");
            return (Criteria) this;
        }

        public Criteria andIsopenstateLessThanOrEqualTo(Integer value) {
            addCriterion("isOpenState <=", value, "isopenstate");
            return (Criteria) this;
        }

        public Criteria andIsopenstateIn(List<Integer> values) {
            addCriterion("isOpenState in", values, "isopenstate");
            return (Criteria) this;
        }

        public Criteria andIsopenstateNotIn(List<Integer> values) {
            addCriterion("isOpenState not in", values, "isopenstate");
            return (Criteria) this;
        }

        public Criteria andIsopenstateBetween(Integer value1, Integer value2) {
            addCriterion("isOpenState between", value1, value2, "isopenstate");
            return (Criteria) this;
        }

        public Criteria andIsopenstateNotBetween(Integer value1, Integer value2) {
            addCriterion("isOpenState not between", value1, value2, "isopenstate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table offOron
     *
     * @mbg.generated do_not_delete_during_merge Wed Dec 28 14:53:42 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table offOron
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}