package com.butterflymob.entity;

public class Offoron {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offOron.isTshortlink
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    private Integer istshortlink;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offOron.isOpenState
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    private Integer isopenstate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offOron.isTshortlink
     *
     * @return the value of offOron.isTshortlink
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    public Integer getIstshortlink() {
        return istshortlink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offOron.isTshortlink
     *
     * @param istshortlink the value for offOron.isTshortlink
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    public void setIstshortlink(Integer istshortlink) {
        this.istshortlink = istshortlink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offOron.isOpenState
     *
     * @return the value of offOron.isOpenState
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    public Integer getIsopenstate() {
        return isopenstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offOron.isOpenState
     *
     * @param isopenstate the value for offOron.isOpenState
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    public void setIsopenstate(Integer isopenstate) {
        this.isopenstate = isopenstate;
    }
}