package com.butterflymob.entity;

public class Shareevent {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shareEvent.eventId
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    private Integer eventid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shareEvent.appPlatform
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    private String appplatform;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shareEvent.appVersion
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    private String appversion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shareEvent.isBack
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    private Integer isback;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shareEvent.isGrant
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    private Integer isgrant;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shareEvent.eventId
     *
     * @return the value of shareEvent.eventId
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    public Integer getEventid() {
        return eventid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shareEvent.eventId
     *
     * @param eventid the value for shareEvent.eventId
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    public void setEventid(Integer eventid) {
        this.eventid = eventid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shareEvent.appPlatform
     *
     * @return the value of shareEvent.appPlatform
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    public String getAppplatform() {
        return appplatform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shareEvent.appPlatform
     *
     * @param appplatform the value for shareEvent.appPlatform
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    public void setAppplatform(String appplatform) {
        this.appplatform = appplatform == null ? null : appplatform.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shareEvent.appVersion
     *
     * @return the value of shareEvent.appVersion
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    public String getAppversion() {
        return appversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shareEvent.appVersion
     *
     * @param appversion the value for shareEvent.appVersion
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    public void setAppversion(String appversion) {
        this.appversion = appversion == null ? null : appversion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shareEvent.isBack
     *
     * @return the value of shareEvent.isBack
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    public Integer getIsback() {
        return isback;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shareEvent.isBack
     *
     * @param isback the value for shareEvent.isBack
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    public void setIsback(Integer isback) {
        this.isback = isback;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shareEvent.isGrant
     *
     * @return the value of shareEvent.isGrant
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    public Integer getIsgrant() {
        return isgrant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shareEvent.isGrant
     *
     * @param isgrant the value for shareEvent.isGrant
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    public void setIsgrant(Integer isgrant) {
        this.isgrant = isgrant;
    }
}