package com.butterflymob.entity;

public class Socialpaltformsetting {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column socialPaltformSetting.appName
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    private String appname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column socialPaltformSetting.comment
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    private String comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column socialPaltformSetting.appKey
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    private String appkey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column socialPaltformSetting.appSecret
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    private String appsecret;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column socialPaltformSetting.appName
     *
     * @return the value of socialPaltformSetting.appName
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    public String getAppname() {
        return appname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column socialPaltformSetting.appName
     *
     * @param appname the value for socialPaltformSetting.appName
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    public void setAppname(String appname) {
        this.appname = appname == null ? null : appname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column socialPaltformSetting.comment
     *
     * @return the value of socialPaltformSetting.comment
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column socialPaltformSetting.comment
     *
     * @param comment the value for socialPaltformSetting.comment
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column socialPaltformSetting.appKey
     *
     * @return the value of socialPaltformSetting.appKey
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    public String getAppkey() {
        return appkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column socialPaltformSetting.appKey
     *
     * @param appkey the value for socialPaltformSetting.appKey
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    public void setAppkey(String appkey) {
        this.appkey = appkey == null ? null : appkey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column socialPaltformSetting.appSecret
     *
     * @return the value of socialPaltformSetting.appSecret
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    public String getAppsecret() {
        return appsecret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column socialPaltformSetting.appSecret
     *
     * @param appsecret the value for socialPaltformSetting.appSecret
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    public void setAppsecret(String appsecret) {
        this.appsecret = appsecret == null ? null : appsecret.trim();
    }
}