package com.butterflymob.entity;

public class Usr {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr.usrId
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    private Integer usrid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr.SocPalt
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    private String socpalt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr.photo
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    private String photo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr.nickname
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr.gender
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr.wherefrom
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    private String wherefrom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr.certInfo
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    private String certinfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr.shareCount
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    private String sharecount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr.usrId
     *
     * @return the value of usr.usrId
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    public Integer getUsrid() {
        return usrid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr.usrId
     *
     * @param usrid the value for usr.usrId
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    public void setUsrid(Integer usrid) {
        this.usrid = usrid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr.SocPalt
     *
     * @return the value of usr.SocPalt
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    public String getSocpalt() {
        return socpalt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr.SocPalt
     *
     * @param socpalt the value for usr.SocPalt
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    public void setSocpalt(String socpalt) {
        this.socpalt = socpalt == null ? null : socpalt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr.photo
     *
     * @return the value of usr.photo
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    public String getPhoto() {
        return photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr.photo
     *
     * @param photo the value for usr.photo
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    public void setPhoto(String photo) {
        this.photo = photo == null ? null : photo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr.nickname
     *
     * @return the value of usr.nickname
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr.nickname
     *
     * @param nickname the value for usr.nickname
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr.gender
     *
     * @return the value of usr.gender
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr.gender
     *
     * @param gender the value for usr.gender
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr.wherefrom
     *
     * @return the value of usr.wherefrom
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    public String getWherefrom() {
        return wherefrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr.wherefrom
     *
     * @param wherefrom the value for usr.wherefrom
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    public void setWherefrom(String wherefrom) {
        this.wherefrom = wherefrom == null ? null : wherefrom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr.certInfo
     *
     * @return the value of usr.certInfo
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    public String getCertinfo() {
        return certinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr.certInfo
     *
     * @param certinfo the value for usr.certInfo
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    public void setCertinfo(String certinfo) {
        this.certinfo = certinfo == null ? null : certinfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr.shareCount
     *
     * @return the value of usr.shareCount
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    public String getSharecount() {
        return sharecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr.shareCount
     *
     * @param sharecount the value for usr.shareCount
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    public void setSharecount(String sharecount) {
        this.sharecount = sharecount == null ? null : sharecount.trim();
    }
}