package com.butterflymob.entity;

import java.util.ArrayList;
import java.util.List;

public class UsrExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table usr
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table usr
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table usr
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    public UsrExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table usr
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUsridIsNull() {
            addCriterion("usrId is null");
            return (Criteria) this;
        }

        public Criteria andUsridIsNotNull() {
            addCriterion("usrId is not null");
            return (Criteria) this;
        }

        public Criteria andUsridEqualTo(Integer value) {
            addCriterion("usrId =", value, "usrid");
            return (Criteria) this;
        }

        public Criteria andUsridNotEqualTo(Integer value) {
            addCriterion("usrId <>", value, "usrid");
            return (Criteria) this;
        }

        public Criteria andUsridGreaterThan(Integer value) {
            addCriterion("usrId >", value, "usrid");
            return (Criteria) this;
        }

        public Criteria andUsridGreaterThanOrEqualTo(Integer value) {
            addCriterion("usrId >=", value, "usrid");
            return (Criteria) this;
        }

        public Criteria andUsridLessThan(Integer value) {
            addCriterion("usrId <", value, "usrid");
            return (Criteria) this;
        }

        public Criteria andUsridLessThanOrEqualTo(Integer value) {
            addCriterion("usrId <=", value, "usrid");
            return (Criteria) this;
        }

        public Criteria andUsridIn(List<Integer> values) {
            addCriterion("usrId in", values, "usrid");
            return (Criteria) this;
        }

        public Criteria andUsridNotIn(List<Integer> values) {
            addCriterion("usrId not in", values, "usrid");
            return (Criteria) this;
        }

        public Criteria andUsridBetween(Integer value1, Integer value2) {
            addCriterion("usrId between", value1, value2, "usrid");
            return (Criteria) this;
        }

        public Criteria andUsridNotBetween(Integer value1, Integer value2) {
            addCriterion("usrId not between", value1, value2, "usrid");
            return (Criteria) this;
        }

        public Criteria andSocpaltIsNull() {
            addCriterion("SocPalt is null");
            return (Criteria) this;
        }

        public Criteria andSocpaltIsNotNull() {
            addCriterion("SocPalt is not null");
            return (Criteria) this;
        }

        public Criteria andSocpaltEqualTo(String value) {
            addCriterion("SocPalt =", value, "socpalt");
            return (Criteria) this;
        }

        public Criteria andSocpaltNotEqualTo(String value) {
            addCriterion("SocPalt <>", value, "socpalt");
            return (Criteria) this;
        }

        public Criteria andSocpaltGreaterThan(String value) {
            addCriterion("SocPalt >", value, "socpalt");
            return (Criteria) this;
        }

        public Criteria andSocpaltGreaterThanOrEqualTo(String value) {
            addCriterion("SocPalt >=", value, "socpalt");
            return (Criteria) this;
        }

        public Criteria andSocpaltLessThan(String value) {
            addCriterion("SocPalt <", value, "socpalt");
            return (Criteria) this;
        }

        public Criteria andSocpaltLessThanOrEqualTo(String value) {
            addCriterion("SocPalt <=", value, "socpalt");
            return (Criteria) this;
        }

        public Criteria andSocpaltLike(String value) {
            addCriterion("SocPalt like", value, "socpalt");
            return (Criteria) this;
        }

        public Criteria andSocpaltNotLike(String value) {
            addCriterion("SocPalt not like", value, "socpalt");
            return (Criteria) this;
        }

        public Criteria andSocpaltIn(List<String> values) {
            addCriterion("SocPalt in", values, "socpalt");
            return (Criteria) this;
        }

        public Criteria andSocpaltNotIn(List<String> values) {
            addCriterion("SocPalt not in", values, "socpalt");
            return (Criteria) this;
        }

        public Criteria andSocpaltBetween(String value1, String value2) {
            addCriterion("SocPalt between", value1, value2, "socpalt");
            return (Criteria) this;
        }

        public Criteria andSocpaltNotBetween(String value1, String value2) {
            addCriterion("SocPalt not between", value1, value2, "socpalt");
            return (Criteria) this;
        }

        public Criteria andPhotoIsNull() {
            addCriterion("photo is null");
            return (Criteria) this;
        }

        public Criteria andPhotoIsNotNull() {
            addCriterion("photo is not null");
            return (Criteria) this;
        }

        public Criteria andPhotoEqualTo(String value) {
            addCriterion("photo =", value, "photo");
            return (Criteria) this;
        }

        public Criteria andPhotoNotEqualTo(String value) {
            addCriterion("photo <>", value, "photo");
            return (Criteria) this;
        }

        public Criteria andPhotoGreaterThan(String value) {
            addCriterion("photo >", value, "photo");
            return (Criteria) this;
        }

        public Criteria andPhotoGreaterThanOrEqualTo(String value) {
            addCriterion("photo >=", value, "photo");
            return (Criteria) this;
        }

        public Criteria andPhotoLessThan(String value) {
            addCriterion("photo <", value, "photo");
            return (Criteria) this;
        }

        public Criteria andPhotoLessThanOrEqualTo(String value) {
            addCriterion("photo <=", value, "photo");
            return (Criteria) this;
        }

        public Criteria andPhotoLike(String value) {
            addCriterion("photo like", value, "photo");
            return (Criteria) this;
        }

        public Criteria andPhotoNotLike(String value) {
            addCriterion("photo not like", value, "photo");
            return (Criteria) this;
        }

        public Criteria andPhotoIn(List<String> values) {
            addCriterion("photo in", values, "photo");
            return (Criteria) this;
        }

        public Criteria andPhotoNotIn(List<String> values) {
            addCriterion("photo not in", values, "photo");
            return (Criteria) this;
        }

        public Criteria andPhotoBetween(String value1, String value2) {
            addCriterion("photo between", value1, value2, "photo");
            return (Criteria) this;
        }

        public Criteria andPhotoNotBetween(String value1, String value2) {
            addCriterion("photo not between", value1, value2, "photo");
            return (Criteria) this;
        }

        public Criteria andNicknameIsNull() {
            addCriterion("nickname is null");
            return (Criteria) this;
        }

        public Criteria andNicknameIsNotNull() {
            addCriterion("nickname is not null");
            return (Criteria) this;
        }

        public Criteria andNicknameEqualTo(String value) {
            addCriterion("nickname =", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameNotEqualTo(String value) {
            addCriterion("nickname <>", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameGreaterThan(String value) {
            addCriterion("nickname >", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameGreaterThanOrEqualTo(String value) {
            addCriterion("nickname >=", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameLessThan(String value) {
            addCriterion("nickname <", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameLessThanOrEqualTo(String value) {
            addCriterion("nickname <=", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameLike(String value) {
            addCriterion("nickname like", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameNotLike(String value) {
            addCriterion("nickname not like", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameIn(List<String> values) {
            addCriterion("nickname in", values, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameNotIn(List<String> values) {
            addCriterion("nickname not in", values, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameBetween(String value1, String value2) {
            addCriterion("nickname between", value1, value2, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameNotBetween(String value1, String value2) {
            addCriterion("nickname not between", value1, value2, "nickname");
            return (Criteria) this;
        }

        public Criteria andGenderIsNull() {
            addCriterion("gender is null");
            return (Criteria) this;
        }

        public Criteria andGenderIsNotNull() {
            addCriterion("gender is not null");
            return (Criteria) this;
        }

        public Criteria andGenderEqualTo(String value) {
            addCriterion("gender =", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotEqualTo(String value) {
            addCriterion("gender <>", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderGreaterThan(String value) {
            addCriterion("gender >", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderGreaterThanOrEqualTo(String value) {
            addCriterion("gender >=", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderLessThan(String value) {
            addCriterion("gender <", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderLessThanOrEqualTo(String value) {
            addCriterion("gender <=", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderLike(String value) {
            addCriterion("gender like", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotLike(String value) {
            addCriterion("gender not like", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderIn(List<String> values) {
            addCriterion("gender in", values, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotIn(List<String> values) {
            addCriterion("gender not in", values, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderBetween(String value1, String value2) {
            addCriterion("gender between", value1, value2, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotBetween(String value1, String value2) {
            addCriterion("gender not between", value1, value2, "gender");
            return (Criteria) this;
        }

        public Criteria andWherefromIsNull() {
            addCriterion("wherefrom is null");
            return (Criteria) this;
        }

        public Criteria andWherefromIsNotNull() {
            addCriterion("wherefrom is not null");
            return (Criteria) this;
        }

        public Criteria andWherefromEqualTo(String value) {
            addCriterion("wherefrom =", value, "wherefrom");
            return (Criteria) this;
        }

        public Criteria andWherefromNotEqualTo(String value) {
            addCriterion("wherefrom <>", value, "wherefrom");
            return (Criteria) this;
        }

        public Criteria andWherefromGreaterThan(String value) {
            addCriterion("wherefrom >", value, "wherefrom");
            return (Criteria) this;
        }

        public Criteria andWherefromGreaterThanOrEqualTo(String value) {
            addCriterion("wherefrom >=", value, "wherefrom");
            return (Criteria) this;
        }

        public Criteria andWherefromLessThan(String value) {
            addCriterion("wherefrom <", value, "wherefrom");
            return (Criteria) this;
        }

        public Criteria andWherefromLessThanOrEqualTo(String value) {
            addCriterion("wherefrom <=", value, "wherefrom");
            return (Criteria) this;
        }

        public Criteria andWherefromLike(String value) {
            addCriterion("wherefrom like", value, "wherefrom");
            return (Criteria) this;
        }

        public Criteria andWherefromNotLike(String value) {
            addCriterion("wherefrom not like", value, "wherefrom");
            return (Criteria) this;
        }

        public Criteria andWherefromIn(List<String> values) {
            addCriterion("wherefrom in", values, "wherefrom");
            return (Criteria) this;
        }

        public Criteria andWherefromNotIn(List<String> values) {
            addCriterion("wherefrom not in", values, "wherefrom");
            return (Criteria) this;
        }

        public Criteria andWherefromBetween(String value1, String value2) {
            addCriterion("wherefrom between", value1, value2, "wherefrom");
            return (Criteria) this;
        }

        public Criteria andWherefromNotBetween(String value1, String value2) {
            addCriterion("wherefrom not between", value1, value2, "wherefrom");
            return (Criteria) this;
        }

        public Criteria andCertinfoIsNull() {
            addCriterion("certInfo is null");
            return (Criteria) this;
        }

        public Criteria andCertinfoIsNotNull() {
            addCriterion("certInfo is not null");
            return (Criteria) this;
        }

        public Criteria andCertinfoEqualTo(String value) {
            addCriterion("certInfo =", value, "certinfo");
            return (Criteria) this;
        }

        public Criteria andCertinfoNotEqualTo(String value) {
            addCriterion("certInfo <>", value, "certinfo");
            return (Criteria) this;
        }

        public Criteria andCertinfoGreaterThan(String value) {
            addCriterion("certInfo >", value, "certinfo");
            return (Criteria) this;
        }

        public Criteria andCertinfoGreaterThanOrEqualTo(String value) {
            addCriterion("certInfo >=", value, "certinfo");
            return (Criteria) this;
        }

        public Criteria andCertinfoLessThan(String value) {
            addCriterion("certInfo <", value, "certinfo");
            return (Criteria) this;
        }

        public Criteria andCertinfoLessThanOrEqualTo(String value) {
            addCriterion("certInfo <=", value, "certinfo");
            return (Criteria) this;
        }

        public Criteria andCertinfoLike(String value) {
            addCriterion("certInfo like", value, "certinfo");
            return (Criteria) this;
        }

        public Criteria andCertinfoNotLike(String value) {
            addCriterion("certInfo not like", value, "certinfo");
            return (Criteria) this;
        }

        public Criteria andCertinfoIn(List<String> values) {
            addCriterion("certInfo in", values, "certinfo");
            return (Criteria) this;
        }

        public Criteria andCertinfoNotIn(List<String> values) {
            addCriterion("certInfo not in", values, "certinfo");
            return (Criteria) this;
        }

        public Criteria andCertinfoBetween(String value1, String value2) {
            addCriterion("certInfo between", value1, value2, "certinfo");
            return (Criteria) this;
        }

        public Criteria andCertinfoNotBetween(String value1, String value2) {
            addCriterion("certInfo not between", value1, value2, "certinfo");
            return (Criteria) this;
        }

        public Criteria andSharecountIsNull() {
            addCriterion("shareCount is null");
            return (Criteria) this;
        }

        public Criteria andSharecountIsNotNull() {
            addCriterion("shareCount is not null");
            return (Criteria) this;
        }

        public Criteria andSharecountEqualTo(String value) {
            addCriterion("shareCount =", value, "sharecount");
            return (Criteria) this;
        }

        public Criteria andSharecountNotEqualTo(String value) {
            addCriterion("shareCount <>", value, "sharecount");
            return (Criteria) this;
        }

        public Criteria andSharecountGreaterThan(String value) {
            addCriterion("shareCount >", value, "sharecount");
            return (Criteria) this;
        }

        public Criteria andSharecountGreaterThanOrEqualTo(String value) {
            addCriterion("shareCount >=", value, "sharecount");
            return (Criteria) this;
        }

        public Criteria andSharecountLessThan(String value) {
            addCriterion("shareCount <", value, "sharecount");
            return (Criteria) this;
        }

        public Criteria andSharecountLessThanOrEqualTo(String value) {
            addCriterion("shareCount <=", value, "sharecount");
            return (Criteria) this;
        }

        public Criteria andSharecountLike(String value) {
            addCriterion("shareCount like", value, "sharecount");
            return (Criteria) this;
        }

        public Criteria andSharecountNotLike(String value) {
            addCriterion("shareCount not like", value, "sharecount");
            return (Criteria) this;
        }

        public Criteria andSharecountIn(List<String> values) {
            addCriterion("shareCount in", values, "sharecount");
            return (Criteria) this;
        }

        public Criteria andSharecountNotIn(List<String> values) {
            addCriterion("shareCount not in", values, "sharecount");
            return (Criteria) this;
        }

        public Criteria andSharecountBetween(String value1, String value2) {
            addCriterion("shareCount between", value1, value2, "sharecount");
            return (Criteria) this;
        }

        public Criteria andSharecountNotBetween(String value1, String value2) {
            addCriterion("shareCount not between", value1, value2, "sharecount");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table usr
     *
     * @mbg.generated do_not_delete_during_merge Wed Dec 28 14:53:42 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table usr
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}