package com.butterflymob.entity;

public class Willshare {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column willShare.count
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    private Integer count;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column willShare.count
     *
     * @return the value of willShare.count
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column willShare.count
     *
     * @param count the value for willShare.count
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    public void setCount(Integer count) {
        this.count = count;
    }
}