package com.butterflymob.mapper;

import com.butterflymob.entity.Appinfo;
import com.butterflymob.entity.AppinfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AppinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appinfo
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    long countByExample(AppinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appinfo
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    int deleteByExample(AppinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appinfo
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    int deleteByPrimaryKey(String appkey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appinfo
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    int insert(Appinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appinfo
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    int insertSelective(Appinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appinfo
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    List<Appinfo> selectByExample(AppinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appinfo
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    Appinfo selectByPrimaryKey(String appkey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appinfo
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    int updateByExampleSelective(@Param("record") Appinfo record, @Param("example") AppinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appinfo
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    int updateByExample(@Param("record") Appinfo record, @Param("example") AppinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appinfo
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    int updateByPrimaryKeySelective(Appinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appinfo
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    int updateByPrimaryKey(Appinfo record);
}