package com.butterflymob.mapper;

import com.butterflymob.entity.Offoron;
import com.butterflymob.entity.OfforonExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OfforonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offOron
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    long countByExample(OfforonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offOron
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    int deleteByExample(OfforonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offOron
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    int insert(Offoron record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offOron
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    int insertSelective(Offoron record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offOron
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    List<Offoron> selectByExample(OfforonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offOron
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    int updateByExampleSelective(@Param("record") Offoron record, @Param("example") OfforonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offOron
     *
     * @mbg.generated Wed Dec 28 14:53:42 CST 2016
     */
    int updateByExample(@Param("record") Offoron record, @Param("example") OfforonExample example);
}